### PR TITLE
Typescript & Node.js improvements based on B-Stefan pull request

### PR DESCRIPTION
**Pull request by k1ng440**
thanks @B-Stefan for typings

### CODE REVIEW

**Comment by k1ng440** [comment]
hey @timdream, can you check please?

**Comment by k1ng440** [comment]
please merge and please create a version in here: https://github.com/timdream/google-oauth2-web-client/releases

**Comment by timdream** [comment]
Looks great! Thank you very much.

Please file separate pull requests for unrelated README changes etc next time.

**Comment by timdream** [comment]
> please merge and please create a version in here: https://github.com/timdream/google-oauth2-web-client/releases

@k1ng440 Just published v0.1.2 on NPM.

**Pull request merged**
